wordpressUsername: admin
wordpressPassword: 12box34
mariadb:
  auth:
    rootPassword: 12root34
    username: bn_wordpress
    password: 12box34
    database: bitnami_wordpress
service:
  type: LoadBalancer
