apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress
  namespace: argocd
spec:
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    chart: wordpress
    targetRevision: 15.1.7  # Specify the chart version to use
    helm:
      valueFiles:
        - values.yaml  # Optional: If you have custom values in your repo
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: wordpress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
